### ISSUE TITLE
numpy/arrayobject.h missing when running setup

### ISSUE THREAD

**Issue by danielzak** [jerkern/pyParticleEst#1]
Hi!

Thanks for a very interesting project. I downloaded and installed it to play around with, and got a fatal warning when running setup.py:

```
fatal error: 'numpy/arrayobject.h' file not found 
```

This makes the compiled C speedup unavailable. If other users encounter this it can be fixed by adding import numpy and include_dirs=[numpy.get_include()] to the extensions import in setup.py, like this:

```
import numpy
...

if (not on_rtd):
extensions = [Extension("pyparticleest/utils/ckalman", ["pyparticleest/utils/ckalman" + ext], include_dirs=[numpy.get_include()]),
              Extension("pyparticleest/utils/cmlnlg_compute", ["pyparticleest/utils/cmlnlg_compute" + ext], include_dirs=[numpy.get_include()])]
```

**Comment by jerkern** [comment]
Thanks for reporting the issue, it should now be fixed in commit 9f2476e0f982d210f262c18832e2618f7d60a06c on the master branch.
