### ISSUE TITLE
Possible missing term in kalman.lognormpdf

### ISSUE THREAD

**Issue by bsugerman** [jerkern/pyParticleEst#2]
I was trying to figure out where your expression for kalman.lognormpdf came from, so I went back to the functional expression
![codecogseqn 1](https://user-images.githubusercontent.com/22836928/28626728-dc89c22a-71ed-11e7-96af-e0409187ad16.gif)

and took the ln of that to find
![codecogseqn 2](https://user-images.githubusercontent.com/22836928/28626732-e3380276-71ed-11e7-8dfb-080fd3d781bc.gif)

I understand how this is the same as your code
     `-0.5 * (S.shape[0] * l2pi + np.linalg.slogdet(S)[1] + np.linalg.solve(S, tmp).T.dot(tmp))`
but if my function _f_ is correct, then your expression is missing that summation `np.sum(tmp)`

Thoughts?

-ben

**Comment by jerkern** [comment]
Hi,

I think your starting point is the source of the discrepancy, the probability density function shouldn't contain the trailing product that you have in your expression:
https://en.wikipedia.org/wiki/Multivariate_normal_distribution#Density_function

**Comment by bsugerman** [comment]
Fair enough. I grabbed the PDF function from here, for what its worth. :-)

http://onlinelibrary.wiley.com/doi/10.1002/asl.128/pdf
