### ISSUE TITLE
examples for paramest

### ISSUE THREAD

**Issue by danbider** [jerkern/pyParticleEst#5]
Hello,

I set an instance of ```StdNonLin``` model, with two fixed parameters, and I was able to use the simulator.Simulator class to do filtering and smoothing successfuly. Now I want to do parameter estimation for these two parameters. Do you by any chance have any examples for that?
I could not get the source code for the paramest class and also encountered the error ```module 'pyparticleest.paramest' has no attribute 'paramest'``` when I tried to run

```import pyparticleest.paramest as paramest```

```est = paramest.paramest.ParamEstimation(model, u=None, y=obs)```

as in the API example.

Thanks for your cool package, looking forward to use it for parameter estimation too.

**Comment by jerkern** [comment]
Does the example in https://github.com/jerkern/pyParticleEst/blob/master/test/manual/paramest/standard_nonlin_model.py work for you?

That should work, but to be honest if I'd written this library today I would have tried setting up the imports a little nicer by adding the big components as import in  `__init__.py`

Pull-requets for (non-breaking) changes to make that nicer is welcome. I unfortunately don't have much time to work on this at the moment, but will of course try to fix any bugs that prevent the library from working.

**Comment by danbider** [comment]
Thanks for your quick response. The example was instructive and after playing with it I was able to get my model working using the pyparticleest.paramest.paramest and pyparticleest.paramest.interfaces modules, without those local imports. I'll keep developing it and keep you posted if anything comes up.
Dan

**Comment by jerkern** [comment]
Sounds great, I'll close this issue, please file a new one if you run into further issues!
